### ISSUE TITLE
How do I launch this?

### ISSUE THREAD

**Issue by pitosalas** [gismo07/coros#1]
I've not seen a standalone docker image like that - in my admitedly limited experience with Docker. I have done `docker pull johannhaselberger/coros` followed by `docker run johannhaselberger/coros:latest`. I am on MacOS.

So far so good. But then I run ./start.sh and I get this error:

```
Removing network utils_default
Creating network "utils_default" with the default driver
Creating coros ... error

ERROR: for coros  Cannot create container for service coros: invalid mount config for type "bind": bind source path does not exist: /ros-persistent-data

ERROR: for coros  Cannot create container for service coros: invalid mount config for type "bind": bind source path does not exist: /ros-persistent-data
ERROR: Encountered errors while bringing up the project.
~/m/c/utils (master *=)
```

**Comment by pitosalas** [comment]
I got this to work. Continuing...

`docker run johannhaselberger/coros:latest`

**Comment by pitosalas** [comment]
Could you just let me know if you prefer not to get emails or issues from users. I just saw that you didn't answer nor close the above issue so maybe you're not even monitoring this...

**Comment by jHaselberger** [comment]
Hi sorry for my late response, actually I was not getting any notification from GitHub.

To solve your problem, please have a look at the `coros/utils/docker-compose.yaml` file. Under volumes there is one volume to store data across container lifecycles:

```
    volumes:
            - type: bind
              source: /ros-persistent-data
              target: /my_ros_data
              volume:
                nocopy: true
```

Make sure, that the source directory exists on your pc. If you want to store the data at a different location, change the path in the docker-compose.yaml.

Also you don't have to run the container with `docker run ...`, `./start.sh` is sufficient.

I hope this is helpful to you.

**Comment by pitosalas** [comment]
Thank you!
