### ISSUE TITLE
xterm goes crazy

### ISSUE THREAD

**Issue by pitosalas** [gismo07/coros#4]
Have you seen this: https://askubuntu.com/questions/1232929/xterm-weird-characters 

I happens when I am using this docker file. Any idea how to fix?

**Comment by jHaselberger** [comment]
Me and my students never came across this issue. Can you please explain when and where this happens? 

This is really strange. I‘m using coros for the most ros projects on my mac and never faced something similar.

**Comment by pitosalas** [comment]
Hi Johann

It happens from time to time when a new xterm window is opened by clicking on the desktop. I wonder whether it is because of this line in .Xresources

xterm*font: *-fixed-*-*-*-20-*

Which I put in because the font that xterm first comes up is so small. That's all I can think of that I did on top of your (excellent) base docker file that has to do with xterm. Here's my derived work: https://github.com/pitosalas/tb3-ros

Also, do you notice that when you go into the vscode server that the terminal shell begins life without running .bashrc? Is there anything to do about that?

Also did you notice the REST error that comes up when running gazebo? Here's the fix:
sed -i -e 's/https:\/\/api.ignitionfuel.org/https:\/\/api.ignitionrobotics.org/g' ~/.ignition/fuel/config.yaml

Thanks again! I never knew about novnc ... It seems to perform a lot better than a regular vnc client, did you notice?

Pito Salas
Brandeis Computer Science
Volen 134
