### ISSUE TITLE
VNC port: "failed to connect to the server" with the modified image 

### ISSUE THREAD

**Issue by Tahir-Rasheed-437** [gismo07/coros#6]
i need some help with the 6080 VNC port. for the default johannhaselberger/coros, its working perfectly fine. But after i launched the image using "./start.sh", i have made some changes in the container, "sudo docker commit <<container_ID>> new_image"  it to a new image. After i want to use the new image with the modifications. I have just replaced the image name  johannhaselberger/coros to new_image in docker-compose.yaml file. Visual studio code can easily launch on the localhost:80 but VNC is failed to connect to server. Sometimes it does connect but mostly i couldn't. Am i missing something? I am a bit new to docker so i might missed something?
Thank you for helping me out.

![Screenshot from 2020-10-20 12-39-05](https://user-images.githubusercontent.com/19925920/96575758-7a0bf180-12d1-11eb-8392-7155d4635551.png)

**Comment by jHaselberger** [comment]
Now that I don't know what changes have been made, it becomes difficult to answer this question.

Is the entrypoint (https://github.com/gismo07/coros/blob/master/entrypoint_code.sh) still the same?

**Comment by Tahir-Rasheed-437** [comment]
hey gism. In the new image, I just added 2 ros packages in home directory that's all. Even if i don't add anything. just if i "./start.sh" the image "johannhaselberger/coros ", and commit it to a "new_image" without any modifications. and then stop and do the "./start.sh" just by changing the name of the image to the "new_image", still i have the same issue. However, visual studio code always working fine

When i commit to the new image, i just used "sudo docker commit <<container_ID>> new_image". Is this the right way?

Yes the entry point is same. I didn't changed anything there.

**Comment by jHaselberger** [comment]
Just in case: can you check that the ports are not used otherwise?

**Comment by jHaselberger** [comment]
Actually I didn't try to commit to a coros image jet.
Can you share your changes, maybe I can try it out myself.

**Comment by Tahir-Rasheed-437** [comment]
yes i checked. ports are only used when i do ./start.sh. otherwise free. 
sure here are the steps that i did:
1. _sudo ./start.sh_
2. _sudo docker exec -it ROS_melodic bash_ 
3. go to home directory /home. just create a ROS package. i create ROS navigation (git clone https://github.com/ros-planning/navigation.git --branch melodic-devel ). build the package. I did _sudo apt-get update_, _rosdep install --from-paths src --ignore-src -r -y_ to install package dependencies and in last _catkin_make_
4. In the new terminal, check the CONTAINER ID _sudo docker ps -a_, and used it to commit a new image _sudo docker commit  <<CONTAINER ID>> new_image_
5. _sudo ./stop.sh_
6. relaunch step 1 by changing the name of the image in docker-compose.yaml "image:new_image"
7. check the VNC http://localhost:6080/vnc.html

I hope you will see the issue. you can skip point 2 and 3. let me know how it goes. Just wondering if for the new image we need to map the ports somehow? or no need?

**Comment by jHaselberger** [comment]
Why `sudo docker exec -it ROS_melodic bash` I think out of the box COROS is not named `ROS_melodic `

**Comment by Tahir-Rasheed-437** [comment]
ah sory i forgot to mention, i changed the container_name in docker-compose.yaml file to "ROS_melodic". you can use the default name "coros"

**Comment by jHaselberger** [comment]
I think in case you want to add some packages its easier to create the new Docker Image by a new Dockerfile like this:

```bash
FROM johannhaselberger/coros

RUN apt-get update && ...
```

Also there are a few things to consider when building Ros packages. As reference you could take the carla-ros-bridge within coros:
```bash
WORKDIR /carla_rb_ws
RUN mkdir src &&\
    cd src &&\
    git clone https://github.com/carla-simulator/ros-bridge.git &&\
    cd ros-bridge &&\
    git submodule update --init

RUN cd /carla_rb_ws &&\
    apt-get update &&\
    rosdep update &&\
    rosdep fix-permissions &&\
    rosdep install --from-paths src --ignore-src -r -y &&\
    rm -rf /var/lib/apt/lists/* &&\
    /bin/bash -c '. /opt/ros/melodic/setup.bash; cd /carla_rb_ws; catkin_make'
```

**Comment by Tahir-Rasheed-437** [comment]
okay and then you recommend to launch this new image using coros (replacing the name of the image in the docker-compose.yaml file with the new generated image)?

**Comment by jHaselberger** [comment]
Yes exactly

**Comment by Tahir-Rasheed-437** [comment]
ok great i am gonna try it today and will update it here. thanks for this idea.

**Comment by jHaselberger** [comment]
Issue seems to be solved

**Comment by Tahir-Rasheed-437** [comment]
i am sorry for a late reply. yes it works perfectly fine this way. Thank you for the tips.
